[package]
name = "arqonhpo-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
arqonhpo-core = { workspace = true }
clap = { workspace = true }
miette = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
