[package]
name = "arqonhpo-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
arqonhpo-core = { path = "../core" }
clap = { version = "4.4", features = ["derive"] }
miette = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
